# Generated by Django 4.1.7 on 2023-02-27 18:41

import apps.User.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=50)),
                ('dateBirth', models.DateTimeField()),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('profilePicture', models.ImageField(null=True, upload_to='profile')),
            ],
        ),
    ]
