# Generated by Django 4.1.7 on 2023-02-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateBirth',
            field=models.DateField(),
        ),
    ]
